import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { NavbarDemo } from "@/components/Navbar/navbar-menu-demo";
import WhatsAppButton from "@/components/floating-icons/whatsapp";
import Chatbot from "@/components/floating-icons/chatbot";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} font-montserrat antialiased bg-white`}
      >
        <header>
          <NavbarDemo />
        </header>
        <main>{children}</main>
        <div className="fixed bottom-42 md:bottom-38 right-8 z-[999]">
          <Chatbot />
          <WhatsAppButton />
        </div>
      </body>
    </html>
  );
}
